version: "2"

checks:
  argument-count:
    config:
      threshold: 5
  file-lines:
    config:
      threshold: 500

plugins:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - XXX
  pep8:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"
    exclude_paths:
      - gwopensci/test_gwopensci.py

ratings:
  paths:
    - "**.py"

exclude_paths:
- versioneer.py
- gwopensci/_version.py
