dist: xenial
language: python

env:
  global:
    secure: "AJ+tw8SSIR1y+QF1purzxs9+2bt2GkJHL+wnrKbHexeM9rd5iGifuSrrJI4SvqUZ3DUHq1B3G4ipwH1IqYq0s/k04f9Q4B8/KQp2nQ+SIxrgEgwpqpqsPB3/eqBpXfJDZyzyIi3EHLHTiGnUMbDODZL1zQhCgKp+FCke8qI31btHkCecRwryzRJVcYBs9Y44SB1eh/80VYOl68RRZzwNeY+rt26lsrC4UcEfpftFNAoqkagQBtW4FbQtP2tlKmRP5UhFOSL9dnsNhNMg9s4Jo+/n1vWrD62W8wktOMia/PnsABXz3m6WUlnJbarOnHFI9mqYUiui2+BWMkWuHpsETUen/by5A18FPMFsuxogIhtmpgtDk21zUpU8BXa4dujN+2TQTkn1tnFvQfEXAyALULLkgHWZjk2Mn+kMCqx6FrbI5Ex6tX4EcEDWb/oYCdpIAh7+9/rP7hPKq0WChBc1r7q6wmPD4HvWOkqCt9kneLKRfZUc/1hSxupgBlj/CZgPf4cLlEDxQ+w/kCGFMZ6oQPIxZ/+6fuQAq2SInXAjVw34M6PAX0ex4hkDWkT7ikiaEc/0+VQeBIOFfMUWFj/c5PJ9F9ps9bJLT89aa11YzpU4Jar1hCDhZ6YR3koFMs2BLK5tMH9on/it/lF4mzqnA3TOfUBT+xsRYAReKsMtUMw="

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - 'nightly'

before_install:
  - pip install pip setuptools --upgrade

install:
  - python -m pip install .

before_script:
  - python -m pip install coveralls "pytest>=2.8" pytest-runner sphinx_rtd_theme numpydoc pytest-socket

script:
  # run unit tests
  - coverage run ./setup.py test

  # run unit tests again with --disable-socket to ensure that tests are marked properly
  - python -m pytest --disable-socket -m "not remote"

  # build documentation
  - cd docs && make html; cd ../

after_success:
  - coveralls

deploy:
  - provider: pypi
    user: duncanmmacleod
    password: ${PYPI_PASSWD}
    distributions: sdist bdist_wheel
    on:
      branch: master
      tags: true
      python: '3.6'
      repo: gwpy/gwosc

cache: pip
