environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
build_script:
  - "%PYTHON%\\python.exe -m pip install ."
test_script:
  - "%PYTHON%\\python.exe setup.py test"
