version: 2

build: &pip-build
  name: Build
  command: python -m pip ${PIP_FLAGS} install .

run-tests: &run-tests
  name: Test
  command: bash -ex ci/test.sh

python: &python-build
  docker:
    - image: python
  steps:
    - checkout
    - run: *pip-build
    - run: *run-tests

jobs:
  python:2.7:
    <<: *python-build
    docker:
      - image: python:2.7
    environment:
      PYTHON_VERSION: "2.7"

  python:3.6:
    <<: *python-build
    docker:
      - image: python:3.6
    environment:
      PYTHON_VERSION: "3.6"

workflows:
  version: 2
  build_and_test:
    jobs:
      - python:2.7
      - python:3.6
