# -- templates --------------

aliases:
  - &attach_workspace
      attach_workspace:
        at: .

  - &store_deb_artifacts
      store_artifacts:
        path: "*.deb"

  - &store_rpm_artifacts
      store_artifacts:
        path: "*.rpm"

  - &store_test_results
      store_test_results:
        path: test-reports

  - &store_test_artifacts
      store_artifacts:
        path: test-reports

  - &build-debian
      run:
        name: Build
        command: |
          set -x;
          apt-get -yqq update;
          apt-get -yqq install \
              dpkg-dev \
              devscripts;
          pushd $(mktemp -d -p .);
          tar -xf ../gwosc-*.tar.gz --strip-components=1;
          # install build dependencies
          mk-build-deps --tool "apt-get -y" --install --remove;
          # build binary package
          dpkg-buildpackage -us -uc -b;
          # mv and install
          popd;
          rm -rf tmp*;
          dpkg --install python*-gwosc*.deb;

  - &build-centos
      run:
        name: Build
        command: |
          set -x;
          yum -y -q update;
          yum -y -q install \
              yum-utils \
              rpm-build \
              python34 \
              python3-rpm-macros;
          # hack version number
          tar -xf gwosc-*.tar.gz;
          rm -rf gwosc-*.tar.gz;
          _version=$(grep "define version" gwosc-*/gwosc.spec | awk '{print $3}');
          mv gwosc-* gwosc-${_version} || true;
          tar -zcf gwosc-${_version}.tar.gz gwosc-${_version};
          rm -rf gwosc-${_version}/;
          # build src rpm
          SRC_RPM=$(rpmbuild -ts gwosc*.tar.gz | cut -d\  -f2);
          # install build dependencies
          yum-builddep -y -q ${SRC_RPM};
          # build binary rpm(s)
          rpmbuild --quiet --define "_rpmdir $(pwd)" --rebuild ${SRC_RPM};
          # mv and install
          mv noarch/*.rpm .;
          rm -rf noarch;
          yum -y -q --nogpgcheck localinstall *.rpm;

  - &prep-test-debian
      run:
        name: Prepare tests
        command: |
          set -x;
          apt-get -yqq install \
              python-pip python3-pip \
              python-pytest python3-pytest \
              python-pytest-cov python3-pytest-cov;

  - &prep-test-centos
      run:
        name: Prepare tests
        command: |
          set -x;
          yum -y -q install \
              python2-pip python34-pip \
              pytest python34-pytest \
              python2-pytest-cov python34-pytest-cov;

  - &test
      run:
        name: Test
        command: |
          set -x;
          mkdir -pv test-reports;
          python${PYTHON_VERSION} -m pip install --upgrade setuptools;
          python${PYTHON_VERSION} -m pip install --upgrade pytest pytest-cov;
          python${PYTHON_VERSION} -m pytest --pyargs gwosc --cov=gwosc --junitxml=test-reports/junit.xml;

  - &codecov
      run:
        name: Submit coverage to codecov
        command: |
          # get OS name from CIRCLE_JOB name
          export IMAGE=$(python${PYTHON_VERSION} -c "print('${CIRCLE_JOB}'.split(':')[-2])")
          # install codecov
          python${PYTHON_VERSION} -m pip install codecov
          # upload coverage
          python${PYTHON_VERSION} -m codecov --flags $(uname) python${PYTHON_VERSION/./} ${IMAGE}

  - &debian
      steps:
        - *attach_workspace
        - *build-debian
        - *prep-test-debian
        - *test
        - *codecov
        - *store_test_results
        - *store_test_artifacts
        - *store_deb_artifacts

  - &centos
      steps:
        - *attach_workspace
        - *build-centos
        - *prep-test-centos
        - *test
        - *codecov
        - *store_test_results
        - *store_test_artifacts
        - *store_rpm_artifacts

# -- jobs -------------------

version: 2
jobs:
  sdist:
    docker:
      - image: python
    steps:
      - checkout
      - run: python setup.py --quiet sdist --dist-dir .
      - persist_to_workspace:
          root: .
          paths:
            - "gwosc-*.tar.gz"

  flake8:
    docker:
      - image: python
    steps:
      - checkout
      - run:
          name: Lint
          command: |
            set -ex;
            python -m pip install "flake8>=3.7.0";
            mkdir -pv test-reports;
            python -m flake8 --output-file test-reports/flake8.txt;
      - run:
          name: Create flake8 report
          when: always
          command: |
            set -ex;
            python -m pip install flake8-junit-report;
            python -m junit_conversor test-reports/flake8.txt test-reports/junit.xml;
      - *store_test_results
      - *store_test_artifacts

  debian:stretch:2.7:
    <<: *debian
    docker:
      - image: ligo/base:stretch
    environment:
      PYTHON_VERSION: "2.7"

  debian:stretch:3.5:
    <<: *debian
    docker:
      - image: ligo/base:stretch
    environment:
      PYTHON_VERSION: "3.5"

  el7:2.7:
    <<: *centos
    docker:
      - image: ligo/base:el7
    environment:
      PYTHON_VERSION: "2.7"

  el7:3.4:
    <<: *centos
    docker:
      - image: ligo/base:el7
    environment:
      PYTHON_VERSION: "3.4"

# -- workflow ---------------

workflows:
  version: 2
  build_and_test:
    jobs:
      - sdist
      - flake8
      - debian:stretch:2.7:
          requires:
            - sdist
      - debian:stretch:3.5:
          requires:
            - sdist
      - el7:2.7:
          requires:
            - sdist
      - el7:3.4:
          requires:
            - sdist
